test: action test을 위한 update 설명 : file 생성 및 경로 확인

diff --git a/.github/workflows/push_build.yml b/.github/workflows/push_build.yml
--- a/.github/workflows/push_build.yml
+++ b/.github/workflows/push_build.yml
@@ -56,6 +56,18 @@ jobs:
       # Set current date as env variable
       - name: Set current date as env variable
         run: echo "datetime=$(date +'%y%m%d%H%M%S')" >> $GITHUB_ENV
+      # test file create
+      - name: Create Test file
+        run: |
+          touch pushFile.sh
+          ls -al
+          pwd
+          git config user.email
+          git config user.name
+      # test repository
+     # - name: Push test another repository in github
+     #   run : |
+
       # build docker container image and push to repository
      # - name: Build and push amazonlinux2
      #   uses: docker/build-push-action@v2
@@ -77,151 +89,151 @@ jobs:
             FROM_IMAGE=centos:7
           tags: |
             ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_centos7
-      - name: Build and push rocky8
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./was-containerization/Dockerfile
-          push: true
-          build-args: |
-            FROM_IMAGE=rockylinux/rockylinux:8.4
-          tags: |
-            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_rocky8
-      - name: Build and push ubuntu1804
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./was-containerization/Dockerfile
-          push: true
-          build-args: |
-            FROM_IMAGE=ubuntu:18.04
-          tags: |
-            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_ubuntu1804
+      #- name: Build and push rocky8
+      #  uses: docker/build-push-action@v2
+      #  with:
+      #    context: .
+      #    file: ./was-containerization/Dockerfile
+      #    push: true
+      #    build-args: |
+      #     FROM_IMAGE=rockylinux/rockylinux:8.4
+      #    tags: |
+      #      ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_rocky8
+      #- name: Build and push ubuntu1804
+      #  uses: docker/build-push-action@v2
+      #  with:
+      #    context: .
+      #    file: ./was-containerization/Dockerfile
+      #    push: true
+      #    build-args: |
+      #      FROM_IMAGE=ubuntu:18.04
+      #    tags: |
+      #      ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_ubuntu1804
     outputs:
       repository: ${{ steps.repository.outputs.lowercase }}
       version: ${{ steps.get-version.outputs.version }}
       datetime: ${{ env.datetime }}
   # test was for each os
-  amazonlinux2:
-    name: "[test] amazonlinux2"
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      # Run conatiner for simple test
-      - name: Docker Run Action
-        id: dockerRunAction
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
-          shell: bash
-          run: |
-            echo "========================="
-            ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
-            ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
-            if [ "$?" -eq "0" ] ; then
-              RESULT=SUCCESS
-            else
-              RESULT=FAIL
-            fi
-            echo '::set-output name=RESULT::'${RESULT}
-            echo "========================="
-      # Check server status
-      - name: PS script Result Check
-        if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('Command Failed [ ps.sh ]')
-  # test was for each os
-  centos7:
-    name: "[test] centos7"
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      # Run conatiner for simple test
-      - name: Docker Run Action
-        id: dockerRunAction
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
-          shell: bash
-          run: |
-            echo "========================="
-            ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
-            ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
-            if [ "$?" -eq "0" ] ; then
-              RESULT=SUCCESS
-            else
-              RESULT=FAIL
-            fi
-            echo '::set-output name=RESULT::'${RESULT}
-            echo "========================="
-      # Check server status
-      - name: PS script Result Check
-        if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('Command Failed [ ps.sh ]')
-  # test was for each os
-  rocky8:
-    name: "[test] rocky8"
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      # Run conatiner for simple test
-      - name: Docker Run Action
-        id: dockerRunAction
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
-          shell: bash
-          run: |
-            echo "========================="
-            ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
-            ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
-            if [ "$?" -eq "0" ] ; then
-              RESULT=SUCCESS
-            else
-              RESULT=FAIL
-            fi
-            echo '::set-output name=RESULT::'${RESULT}
-            echo "========================="
-      # Check server status
-      - name: PS script Result Check
-        if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('Command Failed [ ps.sh ]')
-  # test was for each os
-  ubuntu1804:
-    name: "[test] ubuntu1804"
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      # Run conatiner for simple test
-      - name: Docker Run Action
-        id: dockerRunAction
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
-          shell: bash
-          run: |
-            echo "========================="
-            ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
-            ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
-            if [ "$?" -eq "0" ] ; then
-              RESULT=SUCCESS
-            else
-              RESULT=FAIL
-            fi
-            echo '::set-output name=RESULT::'${RESULT}
-            echo "========================="
-      # Check server status
-      - name: PS script Result Check
-        if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('Command Failed [ ps.sh ]')
+#  amazonlinux2:
+#   name: "[test] amazonlinux2"
+#   runs-on: ubuntu-latest
+#   needs: build
+#   steps:
+#     # Run conatiner for simple test
+#     - name: Docker Run Action
+#       id: dockerRunAction
+#       uses: addnab/docker-run-action@v3
+#       with:
+#         image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
+#         shell: bash
+#         run: |
+#           echo "========================="
+#           ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
+#           ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
+#           if [ "$?" -eq "0" ] ; then
+#             RESULT=SUCCESS
+#           else
+#             RESULT=FAIL
+#           fi
+#           echo '::set-output name=RESULT::'${RESULT}
+#           echo "========================="
+#     # Check server status
+#     - name: PS script Result Check
+#       if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
+#       uses: actions/github-script@v3
+#       with:
+#         script: |
+#           core.setFailed('Command Failed [ ps.sh ]')
+# # test was for each os
+# centos7:
+#   name: "[test] centos7"
+#   runs-on: ubuntu-latest
+#   needs: build
+#   steps:
+#     # Run conatiner for simple test
+#     - name: Docker Run Action
+#       id: dockerRunAction
+#       uses: addnab/docker-run-action@v3
+#       with:
+#         image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
+#         shell: bash
+#         run: |
+#           echo "========================="
+#           ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
+#           ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
+#           if [ "$?" -eq "0" ] ; then
+#             RESULT=SUCCESS
+#           else
+#             RESULT=FAIL
+#           fi
+#           echo '::set-output name=RESULT::'${RESULT}
+#           echo "========================="
+#     # Check server status
+#     - name: PS script Result Check
+#       if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
+#       uses: actions/github-script@v3
+#       with:
+#         script: |
+#           core.setFailed('Command Failed [ ps.sh ]')
+# # test was for each os
+# rocky8:
+#   name: "[test] rocky8"
+#   runs-on: ubuntu-latest
+#   needs: build
+#   steps:
+#     # Run conatiner for simple test
+#     - name: Docker Run Action
+#       id: dockerRunAction
+#       uses: addnab/docker-run-action@v3
+#       with:
+#         image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
+#         shell: bash
+#         run: |
+#           echo "========================="
+#           ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
+#           ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
+#           if [ "$?" -eq "0" ] ; then
+#             RESULT=SUCCESS
+#           else
+#             RESULT=FAIL
+#           fi
+#           echo '::set-output name=RESULT::'${RESULT}
+#           echo "========================="
+#     # Check server status
+#     - name: PS script Result Check
+#       if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
+#       uses: actions/github-script@v3
+#       with:
+#         script: |
+#           core.setFailed('Command Failed [ ps.sh ]')
+# # test was for each os
+# ubuntu1804:
+#   name: "[test] ubuntu1804"
+#   runs-on: ubuntu-latest
+#   needs: build
+#   steps:
+#     # Run conatiner for simple test
+#     - name: Docker Run Action
+#       id: dockerRunAction
+#       uses: addnab/docker-run-action@v3
+#       with:
+#         image: ghcr.io/${{ needs.build.outputs.repository }}:${{ needs.build.outputs.version }}_${{ github.job }}
+#         shell: bash
+#         run: |
+#           echo "========================="
+#           ${LAT_HOME}/servers/${SERVER_NAME}/start.sh
+#           ${LAT_HOME}/servers/${SERVER_NAME}/ps.sh
+#           if [ "$?" -eq "0" ] ; then
+#             RESULT=SUCCESS
+#           else
+#             RESULT=FAIL
+#           fi
+#           echo '::set-output name=RESULT::'${RESULT}
+#           echo "========================="
+#     # Check server status
+#     - name: PS script Result Check
+#       if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
+#       uses: actions/github-script@v3
+#       with:
+#         script: |
+#           core.setFailed('Command Failed [ ps.sh ]')
